version: '3'

volumes:
    logs:
        driver: local

# docker-compose build
# docker-compose up -d
services:
    # http://localhost:7708
    # docker exec -ti pdf-image php --version
    webserver:
        # image: php:7.1-alpine
        # restart: always
        container_name: pdf-image
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t .
        environment:
            docker: "true"
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - 7708:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
            - ./application/config/docker-php.ini:/usr/local/etc/php/conf.d/docker-php.ini
