<h2>Create PDF</h2>
Here you can pack up to 10 images into one PDF.<br />
All images that are uploaded will be deleted immediately after processing.<br />
The images will be saved in the order in which they were uploaded to the PDF.<br />
If an image format is too large for a DIN format, it will automatically be scaled down proportionally.<br />
Each image can be a maximum of 256MB in size.<br />
The file formats JPG and PNG are permitted.<br />
<?php
echo $pdfForm;
if (isset($dateKey)) {
?>
<a class="download" href="<?php echo '/files/pdf/create/Image_' . $dateKey . '.pdf';?>" target="_blank">>>> Your PDF <<<</a>
<?php } ?>
