<h2>Merge PDFs</h2>
<p>
    Here you can combine 2 PDFs into one.<br />
    All data that is uploaded will be deleted immediately after processing.<br />
    All PDF files together may reach a maximum of <?php echo ini_get('upload_max_filesize'); ?>B.<br />
    The file format PDF is permitted.
</p>
<?php
echo $pdfForm;
if (isset($dateKey)) {
?>
<a class="download" href="<?php echo '/files/pdf/merge/PDF_' . $dateKey . '.pdf';?>" target="_blank">>>> Your PDF <<<</a>
<?php } ?>
