<h2>Merge PDFs</h2>
Here you can combine 2 PDFs into one.<br />
All data that is uploaded will be deleted immediately after processing.<br />
Each PDF can be a maximum of 256MB in size.<br />
The file format PDF is permitted.<br />
<?php
echo $pdfForm;
if (isset($dateKey)) {
?>
<a class="download" href="<?php echo '/files/pdf/merge/PDF_' . $dateKey . '.pdf';?>" target="_blank">>>> Your PDF <<<</a>
<?php } ?>
