<?php
$baseHref = ($_SERVER['SERVER_PORT'] == '443' ? 'https' : 'http') . '://' . $_SERVER['SERVER_NAME'] . str_replace('index.php', '', $_SERVER['PHP_SELF']);
$baseHref = isset($_ENV['docker']) && $_ENV['docker'] ? 'http://localhost:7708/' : $baseHref;
?>
<html>
    <head>
        <base href="<?php echo $baseHref; ?>" />
        <link rel="stylesheet" type="text/css" href="files/css/website.css" />
        <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />
        <meta name="keywords" lang="de" content="bild zu pdf, bild wandler, pdf ersteller, pdf vereinen" />
        <meta name="keywords" lang="en" content="image to pdf, image converter, pdf creater, pdf merge" />
        <meta name="keywords" lang="en-us" content="image to pdf, image converter, pdf creater, pdf merge" />
        <title>
            PDF Image
        </title>
    </head>
    <body>
        <div class="website">
            <div class="headline">
                PDF Image
            </div>
            <div class="menu">
                <a href="/" target="_self">Home</a><br />
                <a href="/create/" target="_self">Create PDF</a><br />
                <a href="/merge/" target="_self">Merge PDF</a><br /><br />
                <a href="/wipe.php" target="_blank">Delete Files</a><br />
            </div>
            <div class="content">
                <?php
                    if (file_exists('application/views/' . $page . '.phtml')) {
                        require_once 'application/views/' . $page . '.phtml';
                    } else {
                        require_once 'application/views/error.phtml';
                    }
                ?>
            </div>
        </div>
    </body>
</html>